apiVersion: v1
kind: Secret
metadata:
  name: smart-match-backend-secret
  namespace: smart-match
type: Opaque
stringData:
  FIREBASE_SERVICE_ACCOUNT_JSON: ""
  FIREBASE_SERVICE_ACCOUNT_PATH: ""
  APP_PAYMENT_WEBHOOK_SECRET: change-me
