import React, { useEffect, useState } from 'react';
import { Alert, ScrollView, StyleSheet, Text } from 'react-native';
import { AppButton } from '../../components/AppButton';
import { AppInput } from '../../components/AppInput';
import { companyService } from '../../services/companyService';
import { Company } from '../../types';
import { colors } from '../../theme/colors';

export function CompanyScreen() { const [company, setCompany] = useState<Company | null>(null); const [form, setForm] = useState({ name: '', sector: '', description: '', logoUrl: '', website: '' }); useEffect(() => { companyService.getMine().then((c) => { setCompany(c); setForm({ name: c.name ?? '', sector: c.sector ?? '', description: c.description ?? '', logoUrl: c.logoUrl ?? '', website: c.website ?? '' }); }).catch(() => undefined); }, []); const save = async () => { try { const saved = company ? await companyService.update(company.id, form) : await companyService.create(form); setCompany(saved); Alert.alert('Saved', 'Company saved.'); } catch { Alert.alert('Error', 'Could not save company.'); } }; const set = (key: keyof typeof form, value: string) => setForm({ ...form, [key]: value }); return <ScrollView style={styles.container} contentContainerStyle={styles.content}><Text style={styles.title}>Company</Text><Text style={styles.note}>Validation: {company?.validationStatus ?? 'Not submitted'}\nOnly approved companies can publish offers.</Text><AppInput label="Name" value={form.name} onChangeText={(v) => set('name', v)} /><AppInput label="Sector" value={form.sector} onChangeText={(v) => set('sector', v)} /><AppInput label="Description" value={form.description} onChangeText={(v) => set('description', v)} multiline /><AppInput label="Logo URL" value={form.logoUrl} onChangeText={(v) => set('logoUrl', v)} /><AppInput label="Website" value={form.website} onChangeText={(v) => set('website', v)} /><AppButton title={company ? 'Update company' : 'Create company'} onPress={save} /></ScrollView>; }
const styles = StyleSheet.create({ container: { flex: 1, backgroundColor: colors.background }, content: { padding: 16, gap: 12 }, title: { fontSize: 26, fontWeight: '900', color: colors.text }, note: { backgroundColor: '#fff', borderRadius: 14, padding: 16, color: colors.muted, lineHeight: 22 } });
